import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto py-12 px-4">
        <Card className="glass">
            <CardHeader>
                <CardTitle className="text-3xl text-primary">Terms of Use</CardTitle>
                <CardDescription>Last updated: {new Date().toLocaleDateString()}</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6 prose prose-invert max-w-none text-muted-foreground">
                <p>
                Please read these Terms of Use ("Terms", "Terms of Use") carefully before using the Hyperion Life application (the "Service") operated by us. Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.
                </p>

                <section>
                    <h2 className="text-xl font-semibold text-foreground">1. Accounts</h2>
                    <p>When you create an account with us, you must provide us with information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.</p>
                </section>

                <section>
                    <h2 className="text-xl font-semibold text-foreground">2. Disclaimer of Financial Advice</h2>
                    <p>
                    Hyperion Life is a financial information and planning tool. The Service, including any content generated by our AI, is for informational purposes only. It is not intended as and should not be construed as financial, investment, legal, or tax advice. You should consult with a qualified professional before making any financial decisions. We are not a fiduciary by virtue of your use of the Service.
                    </p>
                </section>
                
                <section>
                    <h2 className="text-xl font-semibold text-foreground">3. Limitation of Liability</h2>
                    <p>
                    In no event shall Hyperion Life, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage.
                    </p>
                </section>
                
                <section>
                    <h2 className="text-xl font-semibold text-foreground">4. Governing Law</h2>
                    <p>These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which the company is based, without regard to its conflict of law provisions.</p>
                </section>

                <section>
                    <h2 className="text-xl font-semibold text-foreground">5. Changes</h2>
                    <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>
                </section>
            </CardContent>
        </Card>
    </div>
  );
}
